version: '3.8'

services:
  registry:
    image: descartesresearch/teastore-registry
    platform: linux/amd64
    ports:
      - "8081:8080"
    restart: unless-stopped

  db:
    image: descartesresearch/teastore-db
    platform: linux/amd64
    ports:
      - "3307:3306"
    restart: unless-stopped

  persistence:
    image: descartesresearch/teastore-persistence
    platform: linux/amd64
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
    depends_on:
      - registry
      - db
    restart: unless-stopped

  auth:
    image: descartesresearch/teastore-auth
    platform: linux/amd64
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
    depends_on:
      - registry
      - persistence
    restart: unless-stopped

  image:
    image: descartesresearch/teastore-image
    platform: linux/amd64
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
    depends_on:
      - registry
      - persistence
    restart: unless-stopped

  recommender:
    image: descartesresearch/teastore-recommender
    platform: linux/amd64
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
    depends_on:
      - registry
      - persistence
    restart: unless-stopped

  webui:
    image: descartesresearch/teastore-webui
    platform: linux/amd64
    container_name: webui
    ports:
      - "8080:8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    depends_on:
      - registry
      - persistence
      - auth
      - image
      - recommender
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
